ChatBlockedMessage: '&8[&7BVC&8] &7Sorry, you can''t chat while vanished!'
ReloadedMessage: '&8[&7BVC&8] &aConfiguration was reloaded!'
NoPermissionMessage: '&8[&7BVC&8] &cSorry, you don''t have permission to do that!'